apiVersion: v1
kind: Namespace
metadata:
  name: app-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app-a
  namespace: app-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-app-a
  namespace: app-a
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app-a
  namespace: app-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-app-a
subjects:
- kind: ServiceAccount
  name: example-app-a
  namespace: app-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: app-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      serviceAccountName: example-app-a
      containers:
        - name: example-app-a
          image: ghcr.io/joshvanl/spiffe-sample-app:dev
          imagePullPolicy: IfNotPresent
          command: [ "sleep", "1000000" ]
          volumeMounts:
          - mountPath: "/.aws"
            name: spiffe
      volumes:
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              aws.spiffe.csi.cert-manager.io/trust-profile: "arn:aws:rolesanywhere:eu-west-3:594830734137:profile/a60cb09f-450e-4a61-84ff-670a66365d29"
              aws.spiffe.csi.cert-manager.io/trust-anchor: "arn:aws:rolesanywhere:eu-west-3:594830734137:trust-anchor/7ef020ad-c7fd-40d8-877f-36c2489c9ba6"
              aws.spiffe.csi.cert-manager.io/role: "arn:aws:iam::594830734137:role/KubeCon-2023-SPIFFE_kubernetes"
              aws.spiffe.csi.cert-manager.io/enable: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app-b
  namespace: app-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-app-b
  namespace: app-b
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app-b
  namespace: app-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-app-b
subjects:
- kind: ServiceAccount
  name: example-app-b
  namespace: app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: app-b
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      serviceAccountName: example-app-b
      containers:
        - name: example-app-b
          image: ghcr.io/joshvanl/spiffe-sample-app:dev
          imagePullPolicy: IfNotPresent
          command: [ "sleep", "1000000" ]
          volumeMounts:
          - mountPath: "/.aws"
            name: spiffe
      volumes:
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              aws.spiffe.csi.cert-manager.io/trust-profile: "arn:aws:rolesanywhere:eu-west-3:594830734137:profile/a60cb09f-450e-4a61-84ff-670a66365d29"
              aws.spiffe.csi.cert-manager.io/trust-anchor: "arn:aws:rolesanywhere:eu-west-3:594830734137:trust-anchor/7ef020ad-c7fd-40d8-877f-36c2489c9ba6"
              aws.spiffe.csi.cert-manager.io/role: "arn:aws:iam::594830734137:role/KubeCon-2023-SPIFFE_kubernetes"
              aws.spiffe.csi.cert-manager.io/enable: "true"
