name: Build

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: kubecon-2023-spiffe
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
    - run: nix run .#check
    - run: nix build .#driver
    - run: nix build .#approver
    - run: nix build .#sample-app
