name: Publish container images

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: kubecon-2023-spiffe
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" nix run .#image-publish
