name: Publish container images

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" nix run .#image-publish
